parameters:
  instagram.api_baseurl: 'https://api.instagram.com'
  instagram.graph_api_baseurl: 'https://graph.instagram.com/v20.0'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenPetersen\Instagram\:
    resource: '../Classes/*'

  # Service Aliases
  SvenPetersen\Instagram\Factory\ApiClientFactoryInterface: '@SvenPetersen\Instagram\Factory\ApiClientFactory'
  SvenPetersen\Instagram\Factory\FeedFactoryInterface: '@SvenPetersen\Instagram\Factory\FeedFactory'

  # Services
  SvenPetersen\Instagram\Service\AccessTokenService:
    arguments:
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
      $apiBaseUrl: '%instagram.api_baseurl%'
      $graphApiBaseUrl: '%instagram.graph_api_baseurl%'

  SvenPetersen\Instagram\Factory\ApiClientFactory:
    arguments:
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
      $apiBaseUrl: '%instagram.graph_api_baseurl%'

  # Commands
  SvenPetersen\Instagram\Command\AccessTokenRefresherCommand:
    tags:
      - name: 'console.command'
        command: 'instagram:accesstoken:refresh-all'
        description: 'Refreshes all accesstokens'

  SvenPetersen\Instagram\Command\ImportPostsCommand:
    tags:
      - name: 'console.command'
        command: 'instagram:import:posts'
        description: 'Imports the latest posts of a given username.'

  SvenPetersen\Instagram\Command\UpdateFeedDataCommand:
    tags:
      - name: 'console.command'
        command: 'instagram:feed:update-data'
        description: 'Updates a given feeds data like followers count, media count, follows count, profile picture url etc.'
